---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
script: "bundle exec rake test"
rvm:
  - 2.5
env:
  - PUPPET_VERSION=5.5.3
  - PUPPET_VERSION=6.10.0
  - PUPPET_VERSION=6.14.0
matrix:
  fast_finish: true
notifications:
  email: false