---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
script: "bundle exec rake test"
rvm:
  - 2.4
env:
  - PUPPET_VERSION=4.6.1
  - PUPPET_VERSION=4.10.0
  - PUPPET_VERSION=5.5.3
matrix:
  fast_finish: true
notifications:
  email: false
matrix:
  exclude:
    - rvm: 2.4
      env: PUPPET_VERSION=5.5.3
    - rvm: 2.4
      env: PUPPET_VERSION=4.6.1
    - rvm: 2.4
      env: PUPPET_VERSION=4.10.0
