---
language: ruby
script: "bundle exec rake test"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.4
env:
  - PUPPET_GEM_VERSION=4.6.0
  - PUPPET_GEM_VERSION=4.10.0
  - PUPPET_GEM_VERSION=5.5.3
matrix:
  fast_finish: true
notifications:
  email: false
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=4.10.0
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=5.5.3
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=4.10.0
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=5.5.3
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=5.5.3
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=4.6.0
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=4.10.0
